config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  resources :teams
  resources :projects
  resources :project_report, only: [:show]
  devise_for :developers
  get 'home/index'
  get 'excecaos/index'

  resources :projects do
    get :generate_code
  end

  resources :developers, only: [:index, :show, :edit, :update]
  resources :developer_report, only: [:show]
  resources :excecaos, only: [:index, :show]
  resources :dono_excecaos, only: [:show, :edit, :update]
  resources :developer_teams, only: [:edit, :update]

  
  root to: 'home#index'
  
  namespace :api do
    namespace :v1 do
      wash_out :wsdl_services

      resources :excecaos, only: [:create]
    end
  end
end
    

app/models/developer.rb
class Developer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :team, optional: true
  
  has_many :dono_excecaos
  
  before_validation :default_admin,  if: -> {self.admin.nil?}

  def ownered_count
    self.dono_excecaos.count
  end

  def solved_count
    count = 0
    self.dono_excecaos.each do |dono_excecao|
      if dono_excecao.solved
        count = count+1
      end
    end
    count
  end

  def done_exceptions
    solved_exceptions = self.solved_count
    
    if solved_exceptions > 0
      solved_percentage = "#{(solved_exceptions.to_f/self.ownered_count)*100}%"
    else
      solved_percentage = "0.0%"
    end

    return solved_percentage  
  end

  def idle?
    if (self.ownered_count - self.solved_count) > 0
      I18n.t('negative')
    else
      I18n.t('positive')
    end
  end 

  private

    def default_admin
      self.admin = true
    end

end

app/controllers/developers_controller.rb
class DevelopersController < ApplicationController
  before_action :set_developer, only: [:show, :edit, :update]
  before_action :get_teams, only: [:edit]
  before_action :authenticate_developer!

  # GET /developers
  # GET /developers.json
  def index
    @developers = Developer.all
  end

  # GET /developers/1
  # GET /developers/1.json
  def show
    excecao_counts = @developer.team.project.excecaos.group(:error).count if @developer.team
    @excecaos_n_atribuido_count = []
    @excecaos_n_atribuido = []
    @excecaos_atribuido_count = []
    @excecaos_atribuido = []
    @excecaos_resolvido_count = []
    @excecaos_resolvido = []
    if @developer.team
      excecao_counts.each do |excecao_count|
        @excecao = Excecao.where(error: excecao_count[0]).last
        
        # binding.pry
        
        if @excecao.dono_excecao.developer_id.nil?
          @excecaos_n_atribuido_count << excecao_count[1]
          @excecaos_n_atribuido << @excecao
        elsif @excecao.dono_excecao.solved == true
          @excecaos_resolvido_count << excecao_count[1]
          @excecaos_resolvido << @excecao
        else
          @excecaos_atribuido_count << excecao_count[1]
          @excecaos_atribuido << @excecao
        end
      end
    end
  end

  # GET /developers/1/edit
  def edit
  end

  # PATCH/PUT /developers/1
  # PATCH/PUT /developers/1.json
  def update
    respond_to do |format|
      if @developer.update(developer_params)
        format.html { redirect_to @developer, notice: 'developer was successfully updated.' }
        format.json { render :show, status: :ok, location: @developer }
      else
        format.html { render :edit }
        format.json { render json: @developer.errors, status: :unprocessable_entity }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_developer
      @developer = Developer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def developer_params
      params.require(:developer).permit(:email, :admin, :team_id)
    end

    def get_teams
      @teams = Team.all
    end

end

app/helpers/developers_helper.rb
module DevelopersHelper
end

app/views/developers/_form.html.erb
<%= form_with(model: @developer, local: true) do |form| %>
  <% if @developer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@developer.errors.count, "error") %> prohibited this developer from being saved:</h2>

      <ul>
      <% @developer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :admin, t('developer.role') %>
    <%= form.select :admin, [[t('developer.admin'), true], [t('developer.developer'), false]] %>
  </div>

  <div class="field">
    <%= form.label :team_id, t('developer.team') %>
    <%= form.select :team_id, @teams.collect { |team| [team.name, team.id] }  %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/developers/edit.html.erb
<h1>Editando Desenvolvedores</h1>

<%= render 'form', team: @developer %>

<%= link_to 'Back', @developer %>

app/views/developers/index.html.erb
<h1><%= t('developers') %></h1>

<table class="responsive nowrap table table-hover" id="all_developers" data-sort="true">
  <thead>
    <tr>
      <th data-data="email">Email</th>
      <th data-data="admin">Admin</th>
      <th data-data="name"><%= t('developer.team') %></th>
      <th data-data="solved"><%= t('team.solved') %></th>
      <th data-data="ownered"><%= t('team.assigned') %></th>
      <th></th>
    </tr>
  </thead>
    <% @developers.each do |developer|%>
      <tr>
        <td><%= developer.email %></td>
        <td><%= developer.admin %></td>
        <td><%= developer.team && developer.team.name %></td>
        <td><%= developer.done_exceptions %></td>
        <td><%= developer.ownered_count %></td>
        <td><%= link_to t('show'), developer %></td>
      </tr>
    <% end %>

</table>

<br>

<%
=begin%>
 <%= link_to 'New developer', new_developer_path %> | 
<%
=end%>

<script>
  $(document).ready( function () {
    $('#all_developers').DataTable();
  } );
</script>

app/views/developers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>email:</strong>
  <%= @developer.email %>
</p>

<p>
  <strong><%= t('developer.Role') %>:</strong>
  <% if @developer.admin %>
    <%= t('developer.Admin') %>
  <% else %>
    <%= t('developer.Developer') %>
  <% end %>
</p>

<p>
  <strong><%= t('developer.team') %>:</strong>
  <%= @developer.team && @developer.team.name %>
</p>


<p>
  <strong><%= t('developer.notAssigned') %> </strong>
</p>

<table class="responsive nowrap table table-hover" id="developer_table_n_atribuido" data-sort="true">
  <thead>
    <tr>
      <th data-data="error">Error</th>
      <th data-data="email"><%= t('project.owner') %></th>
      <th data-data="created_at"><%= t('project.occurrences') %></th>
      <th></th>
    </tr>
  </thead>
  <% @excecaos_n_atribuido.each_with_index do |excecao, index| %>
    <tr>
      <td><%= excecao.error %></td>
      <td><% if excecao.dono_excecao.present? && excecao.dono_excecao.developer.present? %>
        <%= excecao.dono_excecao.developer.email %>
      <% end %></td>
      <td><%= @excecaos_n_atribuido_count[index] %></td>
      <td><%= link_to t('show'), excecao %></td>
    </tr>
  <% end %>
</table>

<%= link_to t('report'), developer_report_url(@developer) %> |
<%= link_to t('edit'), edit_developer_path(@developer) %> | 
<%= link_to t('back'), developers_path %>

<script>
  $(document).ready( function () {
    $('#developer_table_n_atribuido').DataTable();
  } );
</script>