config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  resources :teams
  resources :projects
  resources :project_report, only: [:show]
  devise_for :developers
  get 'home/index'
  get 'excecaos/index'

  resources :projects do
    get :generate_code
  end

  resources :developers, only: [:index, :show, :edit, :update]
  resources :developer_report, only: [:show]
  resources :excecaos, only: [:index, :show]
  resources :dono_excecaos, only: [:show, :edit, :update]
  resources :developer_teams, only: [:edit, :update]

  
  root to: 'home#index'
  
  namespace :api do
    namespace :v1 do
      wash_out :wsdl_services

      resources :excecaos, only: [:create]
    end
  end
end
    

app/models/dono_excecao.rb
class DonoExcecao < ApplicationRecord
  belongs_to :developer, optional: true
  belongs_to :excecao
  
  before_validation :update_created_at

  enum evaluate: {
    very_easy: 0,  
    easy: 1,
    medium: 2,
    hard: 3,
    very_hard: 4
  }

  def update_created_at
    if self.developer_id_changed?
      self.created_at = Time.now
    end
  end
end

app/controllers/dono_excecaos_controller.rb
class DonoExcecaosController < ApplicationController
  before_action :get_dono_excecao, only: [:show, :edit, :update]
  before_action :get_developers, only: [:edit]
  before_action :authenticate_developer!

  def show
  end

  # GET /dono_excecaos/1/edit
  def edit
  end


# PATCH/PUT /dono_excecaos/1
# PATCH/PUT /dono_excecaos/1.json
  def update
    respond_to do |format|
      if @dono_excecao.update(dono_excecao_params)
        format.html { redirect_to @dono_excecao.excecao, notice: 'dono_excecao was successfully updated.' }
        format.json { render :show, status: :ok, location: @dono_excecao.excecao }
      else
        format.html { render :edit }
        format.json { render json: @dono_excecao.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def get_dono_excecao
      @dono_excecao = DonoExcecao.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dono_excecao_params
      params.require(:dono_excecao).permit(:developer_id, :solved, :evaluate, :observation)
    end

    def get_developers
      @developers = Developer.where(team: @dono_excecao.excecao.project.team)
    end
end

app/views/dono_excecaos/_edit.html.erb
<h1><%= t('donoExcecao.editTitle') %></h1>

<%= render 'form', dono_excecao: @dono_excecao %>

app/views/dono_excecaos/_form.html.erb
<%= form_with(model: dono_excecao, local: true) do |form| %>
  <% if dono_excecao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dono_excecao.errors.count, "error") %> prohibited this dono_excecao from being saved:</h2>

      <ul>
      <% dono_excecao.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if current_developer.admin %>
    <div class="field">
      <%= form.label :developer_id %>
      <%= form.select :developer_id, @developers.collect { |developer| [developer.email, developer.id] }  %>
    </div>
  <% end %>

  <% if dono_excecao.developer_id.present? && (current_developer.id == dono_excecao.developer_id) %>
    <div class="field">
      <%= form.check_box :solved %>
      <%= form.label :solved %>
    </div>

    <div class="field">
      <%= form.label :evaluate %>
      <%= form.select :evaluate, DonoExcecao.evaluates.keys.map {|evaluate| [evaluate.titleize, evaluate]} %>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/dono_excecaos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= t('exception') %>:</strong>
  <%= @dono_excecao.excecao.error %>
</p>

<p>
  <strong><%= t('developer') %>:</strong>
  <%= @dono_excecao.developer.email %>
</p>

<%= link_to t('edit'), edit_dono_excecao_path(@dono_excecao) %> |
<%= link_to t('back'), projects_path %>