config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  resources :teams
  resources :projects
  resources :project_report, only: [:show]
  devise_for :developers
  get 'home/index'
  get 'excecaos/index'

  resources :projects do
    get :generate_code
  end

  resources :developers, only: [:index, :show, :edit, :update]
  resources :developer_report, only: [:show]
  resources :excecaos, only: [:index, :show]
  resources :dono_excecaos, only: [:show, :edit, :update]
  resources :developer_teams, only: [:edit, :update]

  
  root to: 'home#index'
  
  namespace :api do
    namespace :v1 do
      wash_out :wsdl_services

      resources :excecaos, only: [:create]
    end
  end
end
    

app/models/project.rb
class Project < ApplicationRecord
  has_one :team
  has_many :excecaos

  validates :code, uniqueness: true

  after_create :generate_code, if: -> { self.code.blank? } 

  def solved_exceptions
    count = 0
    
    self.excecaos.each do |excecao|
      if excecao.dono_excecao.solved
        count = count + 1
      end
    end
    
    return count
  end
  
  def done_exceptions
    count = 0    
    
    self.excecaos.group(:error).count.each do |excecao|
      count = count + excecao[1]
    end
    
    if solved_exceptions > 0
      solved_percentage = "#{(self.solved_exceptions.to_f/count)*100}%"
    else
      solved_percentage = "0.0%"
    end

    return solved_percentage  
  end
  
  def assigned_exceptions
    count = 0

    self.excecaos.each do |excecao|
      if excecao.dono_excecao.solved != true && excecao.dono_excecao.developer_id.present?
        count = count + 1
      end
    end

    return count
  end
  
  def pending_exceptions
    count = 0
    excecao_count = 0

    self.excecaos.group(:error).count.each do |excecao|
      excecao_count = excecao_count + excecao[1]
    end
    
    count = excecao_count - self.assigned_exceptions - self.solved_exceptions
    
    if count > 0
      return count
    else
      return 0
    end
  end
  
  def developers_count
    if self.team.present?
      return self.team.developers.count
    end
  end

  def generate_code
    code = (0...8).map { (65 + rand(26)).chr }.join

    self.update_attributes(code: code)
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_developer!

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    excecao_counts = @project.excecaos.group(:error).count
    @excecaos_n_atribuido_count = []
    @excecaos_n_atribuido = []
    @excecaos_atribuido_count = []
    @excecaos_atribuido = []
    @excecaos_resolvido_count = []
    @excecaos_resolvido = []
    excecao_counts.each do |excecao_count|
      @excecao = Excecao.where(error: excecao_count[0], project_id: @project.id).last
      
      
      if @excecao.dono_excecao.developer_id.nil?
        @excecaos_n_atribuido_count << excecao_count[1]
        @excecaos_n_atribuido << @excecao
      elsif @excecao.dono_excecao.solved == true
        @excecaos_resolvido_count << excecao_count[1]
        @excecaos_resolvido << @excecao
      else
        # binding.pry
        @excecaos_atribuido_count << excecao_count[1]
        @excecaos_atribuido << @excecao
      end
    end
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def generate_code
    @project = Project.find(params[:project_id])

    if @project.generate_code
      respond_to do |format|
        format.html { redirect_to @project, notice: 'Code was successfully generated.' }
        format.json { render :show, status: :ok, location: @project }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name)
    end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1><%= t('projects') %></h1>

<table class="responsive nowrap table table-hover" id="all_projects" data-sort="true">
  <thead>
    <tr>
      <th data-data="name"><%= t('project.name') %></th>
      <th data-data="done"><%= t('exception.done') %></th>
      <th data-data="pending"><%= t('exception.pending') %></th>
      <th data-data="assigned"><%= t('exception.assigned') %></th>
      <th data-data="developers"><%= t('project.developers') %></th>
      <th></th>
    </tr>
  </thead>
    <% @projects.each do |project|%>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.done_exceptions %></td>
        <td><%= project.pending_exceptions %></td>
        <td><%= project.assigned_exceptions %></td>
        <td><%= project.developers_count %></td>
        <td><%= link_to t('show'), project %></td>
      </tr>
    <% end %>

</table>

<br>

<%= link_to t('project.newTitle'), new_project_path %>

<script>
  $(document).ready( function () {
    $('#all_projects').DataTable();
  } );
</script>

app/views/projects/new.html.erb
<h1><%= t('project.newTitle') %></h1>

<%= render 'form', project: @project %>
<%= link_to t('projects'), projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= t('project.name') %>:</strong>
  <%= @project.name %>
  <br>

  <% if current_developer.admin %>
    <strong><%= t('project.access_key') %>:</strong>
    <%= @project.code %>
    <br>
  <% end %>

  <%= button_to t('project.access_key_regenerate'), project_generate_code_path(@project.id), method: :get %>
  <br>

  <%
=begin%>
 <strong>Exceções:</strong> 
<%
=end%>
    <div class="pc-tab">
      <input checked="checked" id="tab1" type="radio" name="pct" />

      <input id="tab2" type="radio" name="pct" />

      <input id="tab3" type="radio" name="pct" />
      <nav>
        <ul>
          <li class="tab1">
            <label for="tab1"><%= t('project.notAssigned') %></label>
          </li>

          <li class="tab2">
            <label for="tab2"><%= t('project.assigned') %></label>
          </li>

          <li class="tab3">
            <label for="tab3"><%= t('project.solved') %></label>
          </li>
        </ul>
      </nav>
      <section>
        <div class="tab1 graph">
          <table class="responsive nowrap table table-hover" id="table_n_atribuido" data-sort="true">
          <thead>
            <tr>
              <th data-data="error">Error</th>
              <th data-data="email"><%= t('project.owner') %></th>
              <th data-data="occurrences"><%= t('project.occurrences') %></th>
              <th data-data="created_at"><%= t('project.created_at_days') %></th>

              <th></th>
            </tr>
          </thead>
          <% @excecaos_n_atribuido.each_with_index do |excecao, index| %>
            <tr>
              <td><%= excecao.error %></td>
              <td><% if excecao.dono_excecao.present? && excecao.dono_excecao.developer.present? %>
                <%= excecao.dono_excecao.developer.email %>
              <% end %></td>
              <td><%= @excecaos_n_atribuido_count[index] %></td>
              <td><%= excecao.created_at_days %> dias</td>
              <td><%= link_to t('show'), excecao %></td>
            </tr>
          <% end %>
        </table>
        </div>

        <div class="tab2 graph">
          <table class="responsive nowrap table table-hover" id="table_atribuido" data-sort="true">
          <thead>
            <tr>
              <th data-data="error">Error</th>
              <th data-data="email"><%= t('project.owner') %></th>
              <th data-data="ocurrences"><%= t('project.occurrences') %></th>
              <th data-data="assigned_at"><%= t('project.assigned_at_days') %></th>
              <th></th>
            </tr>
          </thead>
          <% @excecaos_atribuido.each_with_index do |excecao, index| %>
            <tr>
              <td><%= excecao.error %></td>
              <td><% if excecao.dono_excecao.present? && excecao.dono_excecao.developer.present? %>
                <%= excecao.dono_excecao.developer.email %>
              <% end %></td>
              <td><%= @excecaos_atribuido_count[index] %></td>
              <td><%= excecao.assigned_at_days %> dias</td>
              <td><%= link_to t('show'), excecao %></td>
            </tr>
          <% end %>
        </table>
        </div>

        <div class="tab3 graph">
          <table class="responsive nowrap table table-hover" id="table_pronto" data-sort="true">
          <thead>
            <tr>
              <th data-data="error">Error</th>
              <th data-data="email"><%= t('project.owner') %></th>
              <th data-data="created_at"><%= t('project.occurrences') %></th>
              <th data-data="done_at"><%= t('project.done_at_hours') %></th>
              <th></th>
            </tr>
          </thead>
          <% @excecaos_resolvido.each_with_index do |excecao, index| %>
            <tr>
              <td><%= excecao.error %></td>
              <td><% if excecao.dono_excecao.present? && excecao.dono_excecao.developer.present? %>
                <%= excecao.dono_excecao.developer.email %>
              <% end %></td>
              <td><%= @excecaos_resolvido_count[index] %></td>
              <td><%= excecao.done_at_hours %> horas </td>
              <td><%= link_to t('show'), excecao %></td>
            </tr>
          <% end %>
        </table>
        </div>
      </section>
    </div>
</p>

<%= link_to t('createTeam').upcase, new_team_path %> |
<%= link_to t('report'), project_report_url(@project) %> | 
<%= link_to t('edit'), edit_project_path(@project) %> |
<%= link_to t('back'), projects_path %>


<script>
  $(document).ready( function () {
    $('#table_atribuido').DataTable();
  } );

  $(document).ready( function () {
    $('#table_n_atribuido').DataTable();
  } );

  $(document).ready( function () {
    $('#table_pronto').DataTable();
  } );
</script>