config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  resources :teams
  resources :projects
  resources :project_report, only: [:show]
  devise_for :developers
  get 'home/index'
  get 'excecaos/index'

  resources :projects do
    get :generate_code
  end

  resources :developers, only: [:index, :show, :edit, :update]
  resources :developer_report, only: [:show]
  resources :excecaos, only: [:index, :show]
  resources :dono_excecaos, only: [:show, :edit, :update]
  resources :developer_teams, only: [:edit, :update]

  
  root to: 'home#index'
  
  namespace :api do
    namespace :v1 do
      wash_out :wsdl_services

      resources :excecaos, only: [:create]
    end
  end
end
    

app/models/acao.rb
class Acao < ApplicationRecord
    has_many :excecaos

    has_many :parametros
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/developer.rb
class Developer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :team, optional: true
  
  has_many :dono_excecaos
  
  before_validation :default_admin,  if: -> {self.admin.nil?}

  def ownered_count
    self.dono_excecaos.count
  end

  def solved_count
    count = 0
    self.dono_excecaos.each do |dono_excecao|
      if dono_excecao.solved
        count = count+1
      end
    end
    count
  end

  def done_exceptions
    solved_exceptions = self.solved_count
    
    if solved_exceptions > 0
      solved_percentage = "#{(solved_exceptions.to_f/self.ownered_count)*100}%"
    else
      solved_percentage = "0.0%"
    end

    return solved_percentage  
  end

  def idle?
    if (self.ownered_count - self.solved_count) > 0
      I18n.t('negative')
    else
      I18n.t('positive')
    end
  end 

  private

    def default_admin
      self.admin = true
    end

end

app/models/dono_excecao.rb
class DonoExcecao < ApplicationRecord
  belongs_to :developer, optional: true
  belongs_to :excecao
  
  before_validation :update_created_at

  enum evaluate: {
    very_easy: 0,  
    easy: 1,
    medium: 2,
    hard: 3,
    very_hard: 4
  }

  def update_created_at
    if self.developer_id_changed?
      self.created_at = Time.now
    end
  end
end

app/models/excecao.rb
class Excecao < ApplicationRecord
  belongs_to :acao, optional: true
  belongs_to :project
  
  has_many :parametros
  has_one :dono_excecao
  has_one :http
  has_one :sessao

  after_create :create_dono_excecao
  after_create :send_notification_mail

  def create_dono_excecao 
    DonoExcecao.create(excecao: self)
  end

  def created_at_days
    ((Time.now - self.created_at)/ 1.day).to_i
  end

  def assigned_at_days
    ((Time.now - self.dono_excecao.created_at)/ 1.day).to_i
  end

  def done_at_hours
    ((Time.now - self.dono_excecao.updated_at)/ 1.hour).to_i
  end

  def send_notification_mail
    # self.project.team.developers.each do |developer|
    ExceptionMailer.exception_notification_mail(self.project.team.developers, self).deliver_now
    # end
  end
  
end

app/models/http.rb
class Http < ApplicationRecord
  belongs_to :excecao
end

app/models/obj_sessao.rb
class ObjSessao < ApplicationRecord
  belongs_to :sessao
end

app/models/parametro.rb
class Parametro < ApplicationRecord
  belongs_to :excecao
end

app/models/project.rb
class Project < ApplicationRecord
  has_one :team
  has_many :excecaos

  validates :code, uniqueness: true

  after_create :generate_code, if: -> { self.code.blank? } 

  def solved_exceptions
    count = 0
    
    self.excecaos.each do |excecao|
      if excecao.dono_excecao.solved
        count = count + 1
      end
    end
    
    return count
  end
  
  def done_exceptions
    count = 0    
    
    self.excecaos.group(:error).count.each do |excecao|
      count = count + excecao[1]
    end
    
    if solved_exceptions > 0
      solved_percentage = "#{(self.solved_exceptions.to_f/count)*100}%"
    else
      solved_percentage = "0.0%"
    end

    return solved_percentage  
  end
  
  def assigned_exceptions
    count = 0

    self.excecaos.each do |excecao|
      if excecao.dono_excecao.solved != true && excecao.dono_excecao.developer_id.present?
        count = count + 1
      end
    end

    return count
  end
  
  def pending_exceptions
    count = 0
    excecao_count = 0

    self.excecaos.group(:error).count.each do |excecao|
      excecao_count = excecao_count + excecao[1]
    end
    
    count = excecao_count - self.assigned_exceptions - self.solved_exceptions
    
    if count > 0
      return count
    else
      return 0
    end
  end
  
  def developers_count
    if self.team.present?
      return self.team.developers.count
    end
  end

  def generate_code
    code = (0...8).map { (65 + rand(26)).chr }.join

    self.update_attributes(code: code)
  end

end

app/models/sessao.rb
class Sessao < ApplicationRecord
  belongs_to :excecao
  has_one :obj_sessao
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :project
  has_many :developers
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_developer!

  def index
    redirect_to :controller => 'projects', :action => 'index'
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]
  before_action :get_projects, only: [:new, :edit]
  before_action :authenticate_developer!

  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.all
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
    @developers = Developer.all
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: 'Team was successfully created.' }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1
  # PATCH/PUT /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to @team, notice: 'Team was successfully updated.' }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, notice: 'Team was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_params
      params.require(:team).permit(:name, :project_id)
    end

    def get_projects
      @projects = Project.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/developers_helper.rb
module DevelopersHelper
end

app/helpers/excecaos_helper.rb
module ExcecaosHelper
end

app/helpers/high_charts_helper.rb
module HighChartsHelper
  require 'daru/view'
  def self.newChart(exceptions, title)
    Daru::View.plotting_library = :highcharts
    @data = []
    
    exceptions.each do |exception|
      @data.push([exception[:date], exception[:value] ])
    end
    
    opts = {
      title: {
        text: "#{title}"
      }
    }
    series = [{
      name: 'Solved',
      date: @data.map {|row| row[0]},
      value: @data.map {|row| row[1]}
      # data: @data.map {|row| row[1]}
    }]
    # binding.pry
    dataframe = Daru::DataFrame.new({
      # name: "Solved",
      date: @data.map {|row| row[0]},
      value: @data.map {|row| row[1]}
    })

    Daru::View::Plot.new(dataframe, opts, chart_class: 'stock')
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/_developer_invitation.html.erb
<h2><%= t "devise.invitations.new.header" %></h2>

<%= form_for(resource, as: resource_name, url: invitation_path(resource_name), html: { method: :post }) do |f| %>
  <%= render "devise/shared/error_messages", resource: resource %>

  <% resource.class.invite_key_fields.each do |field| -%>
    <div class="field">
      <%= f.label field %><br />
      <%= f.text_field field %>
    </div>
  <% end -%>


  <div class="actions">
    <%= f.submit t("devise.invitations.new.submit_button") %>
  </div>
<% end %>

app/views/layouts/_menu.html.erb
<% if developer_signed_in? %>
  <div class="vertical-menu">
    <%= link_to t('projects'), projects_path %>
    <% if current_developer.team.present? && current_developer.team.project.present? %>
      <%= link_to t('myProject'), project_path(current_developer.team.project) %>
    <% end %>
    <% if current_developer.admin %>
      <%= link_to t('createNewProject'), new_project_path %>
    <% end %>
  </div>
<% end %>
<% if developer_signed_in? && current_developer.admin %>
  <div class="breakitem"></div>
  <div class="vertical-menu">
    <%= link_to t('teams'), teams_path %>
    <%= link_to t('createTeam'), new_team_path %>
  </div> 
<% end %>
<% if developer_signed_in? && current_developer.admin %>
  <div class="breakitem"></div>
  <div class="vertical-menu">               
    <%= link_to t('developers'), developers_path %>
    <%= link_to t('inviteDeveloper'), new_developer_invitation_path %>
  </div>
<% end %>
<% if developer_signed_in? %>
  <div class="breakitem"></div>    
  <div class="vertical-menu">
    <%= link_to t('logOut'), destroy_developer_session_path, method: :delete %>
  </div>
<% else %>
  <div class="vertical-menu">
    <%= link_to t('logIn'), new_developer_session_path %>
  </div>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tccserver</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true%>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    
    <script type="text/javascript" src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.8/js/jquery.dataTables.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.css">
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

    <%= raw Daru::View.dependent_script(:highcharts) %>


  </head>
<div class="header">
  <div class="header-left">
    <a href="<%= root_path%>"><h1><%= t('appTittle') %></h1></a>
  </div>
  <div class="header-right">
    <%= link_to "en", locale: "en" %>
    <%= link_to "pt", locale: "pt" %>
  </div>
</div>
  <body>
    <div class="container core-page col-lg-4 col-md-4">
      <nav class="navbar navbar-light bg-light hamburguer-menu_container">
        <div class="header">
          <div class="header-left">
            <a href="<%= root_path%>"><h1><%= t('appTittle') %></h1></a>
          </div>
          <div class="header-right">
            <%= link_to "en", locale: "en" %>
            <%= link_to "pt", locale: "pt" %>
          </div>
        </div>
        <div>
        <button class="navbar-toggler toggler-example" type="button" data-toggle="collapse" data-target="#navbarSupportedContent1"
          aria-controls="navbarSupportedContent1" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent1">
          <%= render 'layouts/menu' %>
      </nav>
      
      <div class="vertical-menu_container">
        <%= render 'layouts/menu' %>
        <div class="container core-screen">
        <%- flash.each do |name, msg| -%>
          <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
        <%- end -%>  
          <%= yield %>
        </div>

      </div>
    </div>
  </body>
</html>